#!/usr/bin/env python3
import sys
import os
import json
import math
import re
import subprocess
from pathlib import Path

CONFIG_DIR = os.path.expanduser("~/.config/quickshell")
HYPR_MONITORS_LUA = os.path.expanduser("~/.config/hypr/monitors.lua")


def run_cmd(cmd):
    try:
        return subprocess.run(cmd, capture_output=True, text=True, timeout=8).stdout.strip()
    except (OSError, subprocess.TimeoutExpired):
        return ""


def run_checked(cmd):
    result = subprocess.run(cmd, capture_output=True, text=True, timeout=8)
    if result.returncode != 0 or result.stdout.lstrip().lower().startswith("error"):
        raise RuntimeError((result.stderr or result.stdout).strip() or "Hyprland rechazó la operación")
    return result.stdout.strip()


def eval_hyprland_lua(lua_code):
    return run_checked(["hyprctl", "eval", lua_code])


def is_laptop_display(name):
    return name.lower().startswith(("edp", "lvds", "dsi"))


def parse_mode(mode):
    match = re.fullmatch(r"(\d+)x(\d+)@(\d+(?:\.\d+)?)(?:Hz)?", mode, re.IGNORECASE)
    if not match:
        return None
    w, h, rate = int(match[1]), int(match[2]), float(match[3])
    return (w, h, rate) if w > 0 and h > 0 and math.isfinite(rate) and rate > 0 else None


def mode_string(w, h, rate):
    return f"{w}x{h}@{rate:.2f}Hz"


def describe_monitor(m):
    name = m["name"]
    disabled = bool(m.get("disabled", False))
    width, height = int(m.get("width", 0)), int(m.get("height", 0))
    rate = round(float(m.get("refreshRate", 0)), 2)
    scale = float(m.get("scale", 1)) or 1.0
    transform = int(m.get("transform", 0))
    # EDID range limits are NOT resolution/refresh modes. Never synthesize them.
    available = []
    for raw in m.get("availableModes", []):
        parsed = parse_mode(raw)
        if parsed:
            canonical = mode_string(*parsed)
            if canonical not in available:
                available.append(canonical)
    current = mode_string(width, height, rate) if width > 0 and height > 0 and rate > 0 else "preferred"
    preferred = available[0] if available else current
    if not disabled and current != "preferred" and current not in available:
        available.append(current)
    modes = [{"mode": "preferred", "display": "Automática", "rate": "Auto",
              "resolution": "", "label": "Automática", "is_native": False}]
    for value in sorted(available, key=lambda v: (parse_mode(v)[0] * parse_mode(v)[1], parse_mode(v)[2]), reverse=True):
        w, h, rr = parse_mode(value)
        hz = f"{rr:.2f}".rstrip("0").rstrip(".")
        modes.append({"mode": value, "resolution": f"{w}x{h}", "label": f"{w} × {h}",
                      "rate": f"{hz} Hz", "display": f"{w} × {h} · {hz} Hz", "is_native": False})
    return {
        "name": name, "description": m.get("description") or m.get("model") or name,
        "is_laptop": is_laptop_display(name), "is_external": not is_laptop_display(name),
        "width": width, "height": height, "refresh_rate": rate, "current_mode": current,
        "preferred_mode": preferred, "scale": scale, "transform": transform,
        "focused": bool(m.get("focused", False)), "disabled": disabled,
        "mirror": m.get("mirrorOf") or "none", "modes": modes,
        "available_modes": [x["mode"] for x in modes],
        "resolutions": list(dict.fromkeys(x["resolution"] for x in modes if x["resolution"])),
        "pos_x": m.get("x", 0), "pos_y": m.get("y", 0),
    }


def get_monitors():
    data = json.loads(run_checked(["hyprctl", "monitors", "all", "-j"]))
    if not isinstance(data, list):
        raise RuntimeError("Respuesta de monitores no válida")
    monitors = [describe_monitor(m) for m in data if m.get("name")]
    monitors.sort(key=lambda m: (not m["is_laptop"], m["name"]))
    laptop_count = sum(m["is_laptop"] for m in monitors)
    external_count = len(monitors) - laptop_count
    return {"monitors": monitors, "count": len(monitors), "laptop_count": laptop_count,
            "external_count": external_count, "has_external": external_count > 0,
            "has_laptop": laptop_count > 0}


def monitor_rule(m):
    quote = lambda value: json.dumps(str(value), ensure_ascii=False)
    if m.get("disabled", False):
        return f'hl.monitor({{ output = {quote(m["name"])}, disabled = true }})'
    return ('hl.monitor({ output = ' + quote(m["name"]) + ', mode = ' + quote(m.get("mode", "preferred"))
            + ', position = ' + quote(m.get("pos", "auto")) + ', scale = ' + str(float(m.get("scale", 1)))
            + ', transform = ' + str(int(m.get("transform", 0)))
            + ', mirror = ' + quote(m.get("mirror", "")) + ', disabled = false })')


def save_monitors_lua(monitors):
    path = Path(HYPR_MONITORS_LUA)
    path.parent.mkdir(parents=True, exist_ok=True)
    contents = "-- Autogenerated by MrDemonc-SHELL Monitor Manager\n" + "\n".join(map(monitor_rule, monitors)) + "\n"
    temporary = path.with_suffix(".lua.tmp")
    temporary.write_text(contents)
    os.replace(temporary, path)


def is_session_locked():
    runtime_dir = os.environ.get("XDG_RUNTIME_DIR", "/tmp")
    return os.path.isfile(os.path.join(runtime_dir, "quickshell_lock.active"))


def is_any_monitor_dpms_off():
    try:
        data = json.loads(run_checked(["hyprctl", "monitors", "all", "-j"]))
        enabled = [m for m in data if not m.get("disabled", False)]
        if enabled and not any(m.get("dpmsStatus", True) for m in enabled):
            return True
    except Exception:
        pass
    return False


def is_layout_different(target_layout, current_monitors):
    curr_map = {m["name"]: m for m in current_monitors}
    for target in target_layout:
        name = target["name"]
        curr = curr_map.get(name)
        if curr is None:
            return True
        target_disabled = bool(target.get("disabled", False))
        curr_disabled = bool(curr.get("disabled", False))
        if target_disabled != curr_disabled:
            return True
        if not target_disabled:
            target_mode = target.get("mode")
            curr_mode = curr.get("current_mode")
            if target_mode and curr_mode and target_mode != "preferred" and target_mode != curr_mode:
                return True
            target_pos = target.get("pos")
            curr_pos = f"{curr.get('pos_x', 0)}x{curr.get('pos_y', 0)}"
            if target_pos and target_pos != "auto" and target_pos != curr_pos:
                return True
            target_scale = float(target.get("scale", 1.0))
            curr_scale = float(curr.get("scale", 1.0))
            if abs(target_scale - curr_scale) > 0.01:
                return True
            if int(target.get("transform", 0)) != int(curr.get("transform", 0)):
                return True
            target_mirror = target.get("mirror", "")
            curr_mirror = curr.get("mirror", "")
            if curr_mirror == "none":
                curr_mirror = ""
            if target_mirror != curr_mirror:
                return True
    return False


def apply_layout(layout, save_config=False):
    # One Lua request; do not also send legacy 'keyword monitor' commands.
    # Enable outputs before disabling the previous primary output.
    dpms_was_off = is_any_monitor_dpms_off() or is_session_locked()
    ordered = sorted(layout, key=lambda m: m.get("disabled", False))
    eval_hyprland_lua("\n".join(map(monitor_rule, ordered)))
    if dpms_was_off:
        dpms_off()
    if save_config:
        save_monitors_lua(layout)


def apply_monitor_rule(output, mode="preferred", position="auto", scale=1.0, transform=0, disabled=False, mirror=""):
    apply_layout([{"name": output, "mode": mode, "pos": position, "scale": scale,
                   "transform": transform, "disabled": disabled, "mirror": mirror}])


def active_rule(m):
    mode = m.get("current_mode", "preferred")
    if m.get("disabled") or not parse_mode(mode):
        mode = m.get("preferred_mode", "preferred")
    if not parse_mode(mode):
        raise RuntimeError("Todavía no hay modos disponibles para " + m["name"])
    return {"name": m["name"], "mode": mode, "pos": f'{m.get("pos_x", 0)}x{m.get("pos_y", 0)}',
            "scale": m.get("scale", 1) or 1, "transform": m.get("transform", 0),
            "disabled": False, "mirror": ""}


def arrange_extended(layout):
    x = 0
    for rule in layout:
        if rule.get("disabled") or rule.get("mirror"):
            continue
        width, height, _ = parse_mode(rule["mode"])
        if rule.get("transform", 0) % 2:
            width, height = height, width
        rule["pos"] = f"{x}x0"
        x += math.ceil(width / rule["scale"])
    return layout


def validate_layout(layout):
    rectangles = []
    for rule in layout:
        if rule.get("disabled") or rule.get("mirror"):
            continue
        width, height, _ = parse_mode(rule["mode"])
        if rule.get("transform", 0) % 2:
            width, height = height, width
        x, y = map(int, rule["pos"].split("x"))
        right, bottom = x + width / rule["scale"], y + height / rule["scale"]
        for left2, top2, right2, bottom2 in rectangles:
            if x < right2 and right > left2 and y < bottom2 and bottom > top2:
                raise ValueError("Las pantallas se superponen; selecciona Extender para reorganizarlas")
        rectangles.append((x, y, right, bottom))


def build_preset(preset, monitors):
    if preset not in ("extend", "external_only", "laptop_only", "mirror"):
        raise ValueError("Perfil de pantalla desconocido")
    if not monitors:
        raise ValueError("No se detectaron monitores")
    laptops = [m for m in monitors if m["is_laptop"]]
    externals = [m for m in monitors if m["is_external"]]
    if preset == "external_only" and not externals:
        raise ValueError("No hay monitor externo conectado")
    if preset == "laptop_only" and not laptops:
        raise ValueError("No se detectó pantalla de laptop")
    layout = []
    for m in laptops + externals:
        disabled = (preset == "external_only" and m["is_laptop"]) or (preset == "laptop_only" and m["is_external"])
        layout.append({"name": m["name"], "disabled": True} if disabled else active_rule(m))
    if preset == "mirror":
        primary = layout[0]["name"]
        for rule in layout:
            rule["pos"] = "0x0"
            rule["mirror"] = "" if rule["name"] == primary else primary
        return layout
    return arrange_extended(layout)


def apply_preset(preset_name, save_config=True):
    layout = build_preset(preset_name, get_monitors()["monitors"])
    apply_layout(layout, save_config)
    return {"status": "ok", "preset": preset_name, "message": "Configuración de pantallas aplicada"}


def apply_setting(output, enabled, mode, scale, transform, position="auto", mirror=""):
    monitors = get_monitors()["monitors"]
    target = next((m for m in monitors if m["name"] == output), None)
    if target is None:
        raise ValueError("El monitor ya no está conectado")
    if not math.isfinite(scale) or scale <= 0 or transform not in range(8):
        raise ValueError("Escala u orientación no válida")
    if enabled and mode not in target["available_modes"]:
        raise ValueError("Ese modo no está anunciado por el monitor")
    layout = []
    for m in monitors:
        if m["name"] == output:
            if enabled:
                updated = dict(m, disabled=False, current_mode=target["preferred_mode"] if mode == "preferred" else mode,
                               scale=scale, transform=transform)
                layout.append(active_rule(updated))
            else:
                layout.append({"name": output, "disabled": True})
        elif m["disabled"]:
            layout.append({"name": m["name"], "disabled": True})
        else:
            layout.append(active_rule(m))
    if all(m.get("disabled") for m in layout):
        raise ValueError("Debe quedar al menos una pantalla activa")
    # The UI has no position editor: reflow all active outputs after size/scale changes.
    arrange_extended(layout)
    if position != "auto":
        if not re.fullmatch(r"-?\d+x-?\d+", position):
            raise ValueError("Posición de pantalla no válida")
        next(rule for rule in layout if rule["name"] == output)["pos"] = position
    if mirror and mirror != "none":
        if mirror == output or not any(r["name"] == mirror and not r.get("disabled") for r in layout):
            raise ValueError("Pantalla de referencia para duplicar no válida")
        next(rule for rule in layout if rule["name"] == output)["mirror"] = mirror
    validate_layout(layout)
    apply_layout(layout, save_config=True)
    return {"status": "ok", "message": "Cambios de pantalla aplicados", "output": output}


def handle_topology_change():
    if is_session_locked():
        return {"status": "ignored", "message": "Sesión bloqueada, topología diferida"}
    monitors = get_monitors()["monitors"]
    if not monitors:
        return {"status": "ignored", "message": "Esperando monitores"}
    has_external = any(m["is_external"] for m in monitors)
    if has_external and is_lid_physically_open() is False:
        preset = "external_only"
    else:
        preset = "extend"
    target_layout = build_preset(preset, monitors)
    if not is_layout_different(target_layout, monitors):
        return {"status": "ignored", "message": "La configuración de pantallas ya está aplicada"}
    apply_layout(target_layout, save_config=(preset == "extend"))
    return {"status": "ok", "message": "Pantallas conectadas configuradas automáticamente"}


def get_dpms_bin():
    user_home = os.path.expanduser("~")
    candidates = [
        os.path.join(user_home, ".local", "bin", "shell-dpms"),
        "/usr/local/bin/shell-dpms",
        "/usr/share/mrdemonc-shell/bin/shell-dpms",
        os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "bin", "shell-dpms")
    ]
    for c in candidates:
        if os.path.isfile(c) and os.access(c, os.X_OK):
            return c
    import shutil
    w = shutil.which("shell-dpms")
    if w:
        return w
    return None

def get_lock_bin():
    user_home = os.path.expanduser("~")
    candidates = [
        os.path.join(user_home, ".local", "bin", "shell-lock"),
        "/usr/local/bin/shell-lock",
        "/usr/share/mrdemonc-shell/bin/shell-lock",
        os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "bin", "shell-lock")
    ]
    for c in candidates:
        if os.path.isfile(c) and os.access(c, os.X_OK):
            return c
    import shutil
    w = shutil.which("shell-lock")
    if w:
        return w
    return "shell-lock"

def is_lid_physically_open():
    import glob
    for path in glob.glob("/proc/acpi/button/lid/*/state"):
        try:
            with open(path, "r") as f:
                content = f.read().lower()
                if "open" in content:
                    return True
                elif "close" in content:
                    return False
        except Exception:
            pass
    return None

def check_lid_debounce(event_name):
    import time
    runtime_dir = os.environ.get("XDG_RUNTIME_DIR", "/tmp")
    stamp_file = os.path.join(runtime_dir, "shell_lid_last_event")
    now = time.time()

    if os.path.exists(stamp_file):
        try:
            with open(stamp_file, "r") as f:
                line = f.read().strip()
                if ":" in line:
                    parts = line.split(":", 1)
                    last_time = float(parts[0])
                    last_event = parts[1]
                    # Descartar rebote si es el mismo evento dentro de 1.2 segundos
                    if event_name == last_event and (now - last_time) < 1.2:
                        return False
                    # Si es evento contrario en menos de 0.8s, verificar estado fisico por hardware
                    if (now - last_time) < 0.8:
                        phys = is_lid_physically_open()
                        if phys is not None:
                            if event_name == "lid_open" and not phys:
                                return False
                            if event_name == "lid_close" and phys:
                                return False
        except Exception:
            pass

    try:
        with open(stamp_file, "w") as f:
            f.write(f"{now}:{event_name}")
    except Exception:
        pass
    return True

def dpms_off():
    bin_path = get_dpms_bin()
    if bin_path:
        run_cmd([bin_path, "off"])
    else:
        eval_hyprland_lua('hl.dispatch(hl.dsp.dpms({ action = "off" }))')

def dpms_on():
    bin_path = get_dpms_bin()
    if bin_path:
        run_cmd([bin_path, "on"])
    else:
        eval_hyprland_lua('hl.dispatch(hl.dsp.dpms({ action = "on" }))')

def handle_lid_close():
    if not check_lid_debounce("lid_close"):
        return {"status": "debounced", "action": "ignored"}

    phys = is_lid_physically_open()
    if phys is True:
        return {"status": "ignored", "reason": "lid_physically_open"}

    data = get_monitors()
    monitors = data.get("monitors", [])
    laptop = next((m for m in monitors if m.get("is_laptop", False)), None)
    externals = [m for m in monitors if m.get("is_external", False)]

    # Si hay pantalla externa conectada (HDMI, DisplayPort, etc.):
    # Modo clamshell: NO bloquear, apagar sólo la pantalla integrada de la laptop y mantener la externa activa
    # IMPORTANTE: NO guardar en monitors.lua para evitar bucles de recarga de Hyprland
    if externals:
        target_layout = build_preset("external_only", monitors)
        if is_layout_different(target_layout, monitors):
            res = apply_layout(target_layout, save_config=False)
        else:
            res = {"status": "ok", "message": "Ya en modo external_only"}
        if not is_session_locked():
            dpms_on()
        return res
    else:
        # Solo laptop sin pantalla externa: bloquear inmediatamente y apagar el display
        lock_bin = get_lock_bin()
        result = subprocess.run([lock_bin], check=False)
        if result.returncode != 0:
            return {"status": "error", "message": "No se confirmó el bloqueo"}
        if is_lid_physically_open() is True:
            dpms_on()
            return {"status": "ignored", "reason": "lid_reopened"}
        dpms_off()
        return {"status": "ok", "action": "locked_and_dpms_off"}

def handle_lid_open():
    if not check_lid_debounce("lid_open"):
        return {"status": "debounced", "action": "ignored"}

    phys = is_lid_physically_open()
    if phys is False:
        return {"status": "ignored", "reason": "lid_physically_closed"}

    dpms_on()
    data = get_monitors()
    monitors = data.get("monitors", [])
    laptop = next((m for m in monitors if m.get("is_laptop", False)), None)
    externals = [m for m in monitors if m.get("is_external", False)]

    # Al abrir la tapa: NO guardar en monitors.lua. Aplicar en memoria via IPC.
    if laptop and externals:
        res = apply_preset("extend", save_config=False)
    else:
        if laptop and laptop.get("disabled", False):
            apply_monitor_rule(laptop["name"], mode="preferred", position="0x0", scale=1.0, disabled=False)
            run_cmd(["hyprctl", "dispatch", "focusmonitor", laptop["name"]])
        res = {"status": "ok", "action": "laptop_active"}
    dpms_on()
    return res

def main():
    if len(sys.argv) < 2:
        print(json.dumps(get_monitors(), indent=2))
        return

    action = sys.argv[1]

    if action == "get":
        print(json.dumps(get_monitors()))
        return

    if action in ("lid_close", "lid_open", "auto"):
        result = {"lid_close": handle_lid_close, "lid_open": handle_lid_open, "auto": handle_topology_change}[action]()
        print(json.dumps(result))
        return

    if action == "preset":
        if len(sys.argv) < 3:
            print(json.dumps({"status": "error", "message": "Falta el nombre del preset"}))
            return
        res = apply_preset(sys.argv[2])
        print(json.dumps(res))
        return

    if action == "set":
        import argparse
        parser = argparse.ArgumentParser()
        parser.add_argument("action")
        parser.add_argument("--output", required=True)
        parser.add_argument("--enable", action="store_true")
        parser.add_argument("--disable", action="store_true")
        parser.add_argument("--mode", default="preferred")
        parser.add_argument("--scale", type=float, default=1.0)
        parser.add_argument("--pos", default="auto")
        parser.add_argument("--transform", type=int, default=0)
        parser.add_argument("--mirror", default="")
        args = parser.parse_args()

        result = apply_setting(args.output, not args.disable, args.mode, args.scale, args.transform, args.pos, args.mirror)
        print(json.dumps(result))
        return

if __name__ == "__main__":
    try:
        if len(sys.argv) > 1 and sys.argv[1] in ("lid_close", "lid_open", "auto", "set", "preset"):
            import fcntl
            with open(os.path.join(os.environ["XDG_RUNTIME_DIR"], "shell_lid.lock"), "w") as guard:
                fcntl.flock(guard, fcntl.LOCK_EX)
                main()
        else:
            main()
    except (ValueError, RuntimeError, OSError, subprocess.TimeoutExpired) as error:
        print(json.dumps({"status": "error", "message": str(error)}))
        sys.exit(1)
