# Generado automáticamente por Quickshell Theme Manager
foreground #eceff4
background #1a1d24
selection_foreground #eceff4
selection_background #282d38

cursor #88c0d0
cursor_text_color #1a1d24

active_border_color #88c0d0
inactive_border_color #353b49
active_tab_background #88c0d0
active_tab_foreground #1a1d24
inactive_tab_background #14161d
inactive_tab_foreground #d8dee9

# Paleta ANSI estándar
color0 #14161d
color1 #bf616a
color2 #a3be8c
color3 #ebcb8b
color4 #81a1c1
color5 #b48ead
color6 #88c0d0
color7 #eceff4

# Paleta ANSI brillante
color8 #7b889b
color9 #bf616a
color10 #a3be8c
color11 #ebcb8b
color12 #81a1c1
color13 #b48ead
color14 #88c0d0
color15 #d8dee9
