# ==============================================================================
#  MrDemonc-SHELL: Hypridle Configuration
# ==============================================================================

general {
    lock_cmd = shell-lock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

# 1. Reducir brillo tras 5 minutos de inactividad
listener {
    timeout = 300
    on-timeout = brightnessctl -s set 15%
    on-resume = brightnessctl -r
}

# 2. Bloquear la pantalla automáticamente tras 10 minutos
listener {
    timeout = 600
    on-timeout = loginctl lock-session
}

# 3. Apagar la pantalla tras 15 minutos
listener {
    timeout = 900
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}
