# Generado automáticamente por Quickshell Theme Manager
$bg = rgba(40, 40, 40, 1.0)
$surface = rgba(29, 32, 33, 0.85)
$surface_alpha = rgba(29, 32, 33, 0.70)
$primary = rgba(215, 153, 33, 1.0)
$primary_dim = rgba(215, 153, 33, 0.70)
$text = rgba(235, 219, 178, 1.0)
$subtext = rgba(213, 196, 161, 1.0)
$overlay = rgba(146, 131, 116, 1.0)
$success = rgba(184, 187, 38, 1.0)
$danger = rgba(251, 73, 52, 1.0)
$warning = rgba(250, 189, 47, 1.0)
