-- Autogenerated by MrDemonc-SHELL Monitor Manager
hl.monitor({ output = "eDP-1", disabled = true })
hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@120.00Hz",
    position = "0x0",
    scale = 1.0,
    transform = 0,
    mirror = "",
    disabled = false,
})
